addpath( ...
    'submodules/AndorControl',...
    'submodules/CANControl',...
    'submodules/HDF5Storage',...
    'submodules/NewportXPS',...
    'submodules/NewportXPS/XPS Scripted Operation',...
    'submodules/NewportXPS/xpsMatlabDriver_x64',...
    'submodules/NewportXPS/xpsMatlabDriver_x64/m'...
);