fp = mfilename('fullpath');
[pathstr,name,ext] = fileparts(fp);

paths = {
    'submodules/AndorControl',...
    'submodules/CANControl',...
    'submodules/HDF5Storage',...
    'submodules/NewportXPS',...
    'submodules/NewportXPS/XPS_ScriptedOperation',...
    'submodules/NewportXPS/xpsMatlabDriver_x64',...
    'submodules/NewportXPS/xpsMatlabDriver_x64/m'...
};
for jj = 1:length(paths)
    addpath([pathstr filesep paths{jj}]);
end